seed: 3756

dataset:
  name: "qwen_twitter"
  root_path: "/media/shared_d/lyq/DataSet/FakeNews/twitter"
  use_cache: True
  shuffle: True
  max_len: 50
  batch_size: 64

model:
  name: "ARGVL"
  version: "1"
  text_encoder_path: "/media/shared_d/lyq/Model/roberta-base"
  image_encoder_path: "/media/shared_d/lyq/Model/swinv2-tiny-patch4-window16-256"
  # model parameters
  emb_dim: 768
  num_heads: 1
  dropout: 0.2
  mlp:
    dims: [384]


  # ['train']
train:
  device:
    use_cuda: True
    use_multi: True
    gpu: 0
  num_epochs: 100
  save_param_dir: "param_model"
  lr: !!float 5e-5
  patience: 5
  weight_decay: !!float 5e-5
  rationale_usefulness_evaluator_weight: 1.5
  llm_judgment_predictor_weight: 0.5
  early_stopping_metric_name: 'f1_macro'
  LossWeight:
    classify: 0.0
    usefulPred: 3.0

logging:
  level: "INFO"
  log_dir: "logs/log/"
  json_result_dir: "logs/json"

