seed: 3756

dataset:
  name: "qwen_weibo"
  root_path: "/home/lyq/DataSet/FakeNews/weibo_dataset"
  use_cache: True
  shuffle: True
  max_len: 256
  batch_size: 64

model:
  name: "ARGVL"
  version: "1"
  text_encoder_path: "/home/lyq/Model/chinese-bert-wwm-ext"
  image_encoder_path: "/home/lyq/Model/swinv2-tiny-patch4-window16-256"
  # model parameters
  emb_dim: 768
  num_heads: 1
  dropout: 0.2
  mlp:
    dims: [384]


train:
  device:
    use_cuda: True
    use_multi: True
    gpu: 0
  num_epochs: 50
  save_param_dir: "param_model"
  lr: !!float 2e-5
  patience: 5
  weight_decay: !!float 5e-5
  rationale_usefulness_evaluator_weight: 2.2
  llm_judgment_predictor_weight: 1.8
  early_stopping_metric_name: 'f1_macro'
  LossWeight:
    classify: 0.0
    usefulPred: 3.0

logging:
  level: "INFO"
  log_dir: "logs/log/"
  json_result_dir: "logs/json"

