seed: 3757

dataset:
  name: "qwen_twitter"
  root_path: "/media/shared_d/lyq/DataSet/FakeNews/twitter"
  use_cache: True
  shuffle: True
  max_len: 256
  batch_size: 128

model:
  name: "ContrastiveModel"
  version: "1"
  temperature: 0.07
  text_encoder_path: "/media/shared_d/lyq/Model/roberta-base"
  image_encoder_path: "/media/shared_d/lyq/Model/swinv2-tiny-patch4-window16-256"
  # model parameters
  sim_emb: 768


  # ['train']
train:
  device:
    use_cuda: True
    use_multi: False
    gpu: 1
  num_epochs: 200
  save_param_dir: "param_model"
  lr: !!float 4e-4
  patience: 5
  weight_decay: !!float 5e-5
  early_stopping_metric_name: 'val_loss'

logging:
  level: "INFO"
  log_dir: "logs/log/"
  json_result_dir: "logs/json"

